name: Jest Tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: cd viewer && yarn
      - name: Run tests
        run: cd viewer && yarn test
